---
# ! NOTE: do not use this file in production

services:
  database:
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    restart: always
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_user
      MONGO_INITDB_ROOT_PASSWORD: my_safe_password
    networks:
      - database
  backend:
    depends_on:
      - database
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - database
      - backend
    volumes:
      - .:/app
    command: ["uvicorn", "--port", "8080", "--host", "0.0.0.0", "src.main:app", "--reload"]
networks:
  database:
    name: mongodb
    internal: true
  backend:
    name: backend
    internal: false