---
# ! NOTE: do not use this file in production

services:
  database:
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    restart: always
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_user
      MONGO_INITDB_ROOT_PASSWORD: my_safe_password
    networks:
      - unseen
  backend:
    depends_on:
      - database
      - cache
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - unseen
      - realworld
    volumes:
      - .:/app
    command: ["uvicorn", "--port", "8080", "--host", "0.0.0.0", "src.main:app", "--reload"]
  cache:
    container_name: cache
    image: redis:7.2.5
    volumes:
      - ./volumes/redis/:/data
    ports:
      - 6379:6379
    networks:
      - unseen
networks:
  unseen:
    name: Unseen
    internal: true
  realworld:
    name: Real world
    internal: false